# Generated by Django 3.1.11 on 2025-03-04 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=255)),
                ('ingestion_id', models.CharField(max_length=255, unique=True)),
                ('ingestion_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ingestion_log',
            },
        ),
        migrations.CreateModel(
            name='JSONFile',
            fields=[
                ('ingestion_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uploader_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('batch_id', models.CharField(max_length=255)),
                ('unique_grant_id', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jsonfile',
            },
        ),
        migrations.CreateModel(
            name='SourceMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_url', models.CharField(max_length=255)),
                ('date_of_arrival', models.DateField()),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_of_site_updates', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')], max_length=20)),
                ('site_last_checked', models.DateField()),
                ('source_file_upload', models.CharField(blank=True, max_length=255, null=True)),
                ('json_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('json_upload_date', models.DateField(blank=True, null=True)),
                ('sup_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sme_comments', models.TextField(blank=True, null=True)),
                ('screenshots_taken', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=10, null=True)),
                ('qa_comment', models.TextField(blank=True, null=True)),
                ('qa_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qa_issue', models.CharField(blank=True, choices=[('batchid', 'Batch ID'), ('title', 'Title'), ('homepage', 'Homepage'), ('other', 'Other')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'source_metadata',
            },
        ),
    ]
