# Generated by Django 3.1.12 on 2025-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0002_auto_20241218_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='uploader_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='batch_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
