# Generated by Django 3.1.12 on 2025-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0003_auto_20250103_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfile',
            name='uploader_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
