# Generated by Django 3.1.12 on 2025-01-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0004_auto_20250103_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='file_type',
            field=models.CharField(default='unknwon', max_length=50),
            preserve_default=False,
        ),
    ]
