# Generated by Django 3.1.12 on 2025-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0005_jsonfile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonfile',
            name='id',
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='ingestion_id',
            field=models.CharField(default='unkwon', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonfile',
            name='unique_grant_id',
            field=models.CharField(default='unknwon', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jsonfile',
            name='uploader_name',
            field=models.CharField(max_length=255),
        ),
    ]
