# Generated by Django 5.1.5 on 2025-01-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
