# Generated by Django 3.1.12 on 2025-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ingestion_id', models.CharField(max_length=100, unique=True)),
                ('item_id', models.IntegerField()),
                ('batch_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ingestion_logs',
            },
        ),
    ]
