"""
Django settings for json_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
USE_X_FORWARDED_HOST = True


#<<<<<<< HEAD
# from django.conf import settings
# from django.conf.urls.static import static
SITE_ID = 1
# if settings.DEBUG:
#=======

#from django.conf import settings
#from django.conf.urls.static import static
#if settings.DEBUG:
#>>>>>>> ed162d022ff3746cae44ae94bef7bcf6f8ae0812
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

from mongoengine import connect
import mongoengine
MONGO_DATABASE = 'CMS'  # The name of your MongoDB database
MONGO_HOST = '127.0.0.1'  # MongoDB host
MONGO_PORT = 27017

#new settings update on 22/1/2025


# MongoDB configuration (assuming MongoDB is running locally)
mongoengine.connect(MONGO_DATABASE, host=MONGO_HOST, port=MONGO_PORT)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@vs2$wy%^x9!q_t5=x26%klt2)3r*l55p1sxs!npmp^aun@ge'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False for production, but make sure ALLOWED_HOSTS is configured

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','35.245.126.111']  # Replace with your domains or IPs as needed



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'json_app',
    'allauth.account',
    'allauth.socialaccount',
   

]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


DATABASE_ROUTERS = ['json_project.migration_router.MongoDBRouter']




LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'
# # Default Auto Field
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'  # Redirect users after successful login
LOGOUT_REDIRECT_URL = '/'  # Redirect users after logout
ACCOUNT_LOGOUT_ON_GET = True  # Logout immediately when the logout URL is accessed
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Change as needed
ACCOUNT_EMAIL_REQUIRED = True  # Set to True if email is mandatory for login
 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'allauth.middleware.AccountMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'json_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'json_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'json_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    },
    'mongo': {
        'ENGINE': 'djongo',
        'NAME': MONGO_DATABASE,
        'HOST': MONGO_HOST,
        'PORT': MONGO_PORT,
         'username': 'admin',
         'password': 'DDNAdminR!098',
         'authSource': 'admin',
    }
}



#commenting this for backend check
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / "db.sqlite3",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# from pathlib import Path
# import os

# # Base Directory
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Secret Key
# SECRET_KEY = 'django-insecure-k@vs2$wy%^x9!q_t5=x26%klt2)3r*l55p1sxs!npmp^aun@ge'

# # Debug Mode
# DEBUG = True  # Set to False for production

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# # Installed Apps
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'json_app',
# ]

# # Middleware
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# # URL Configurations
# ROOT_URLCONF = 'json_project.urls'

# # Templates
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'json_app/templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# # WSGI Application
# WSGI_APPLICATION = 'json_project.wsgi.application'

# # Database Configuration for MongoDB
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',  # Ensure djongo is installed
#         'NAME': 'test',   # Your MongoDB database name
#         'HOST': 'localhost',
#         'PORT': 27017,
#         # Uncomment and add authentication if required:
#         # 'USER': 'your_username',
#         # 'PASSWORD': 'your_password',
#         # 'AUTH_SOURCE': 'admin',
#     }
# }

# # Password Validation
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # Static Files
# STATIC_URL = 'static/'

# # Default Auto Field
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
